export const USERNAME_INPUT = '#user-name';
export const PASSWORD_INPUT = '#password';
export const LOGIN_BUTTON = '#login-button';
export const ERROR_MESSAGE = '.error-message-container';

export const SORT_SELECT = '.product_sort_container';
export const INVENTORY_ITEM = '.inventory_item';
export const INVENTORY_ITEM_NAME = '.inventory_item_name';
export const INVENTORY_ITEM_PRICE = '.inventory_item_price';
export const ADD_TO_CART_BUTTON = '.btn_primary.btn_inventory';
export const REMOVE_FROM_CART_BUTTON = '#remove-sauce-labs-bolt-t-shirt';
export const SHOPPING_CART_BADGE = '.shopping_cart_badge';
export const SHOPPING_CART_CONTAINER = '#shopping_cart_container';
export const CART_ITEM = '.cart_item';
export const CART_ITEM_NAME = '.cart_item_label a';
export const CART_ITEM_DESCRIPTION = '.cart_item_label .inventory_item_desc';
export const CART_ITEM_PRICE = '.cart_item_label .inventory_item_price';
export const CONTINUE_SHOPPING_BUTTON = '[data-test="continue-shopping"]';
export const CHECKOUT_BUTTON = '[data-test="checkout"]';
export const CHECKOUT_FIRST_NAME_INPUT = '#first-name';
export const CHECKOUT_LAST_NAME_INPUT = '#last-name';
export const CHECKOUT_ZIP_CODE_INPUT = '#postal-code';
export const CHECKOUT_CONTINUE_BUTTON = '[data-test="continue"]';
export const CHECKOUT_CANCEL_BUTTON = '[data-test="cancel"]';
export const CHECKOUT_FINISH_BUTTON = '[data-test="finish"]';
export const CHECKOUT_COMPLETE_MESSAGE = '.complete-header';
